name: Deploy

on: [push]

jobs:
  resume-action:
    runs-on: ubuntu-latest
    name: Resume Action Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Resume Template
        uses: rennancockles/resume-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          directory: 'data'
          cname: 'resume.r3ck.com.br'
