name: Deploy

on: [push]

jobs:
  resume-action:
    runs-on: ubuntu-latest
    name: Resume Action Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resume Template
        uses: rennancockles/resume-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          resume_file: 'data/resume.json'
          cname: 'resume.r3ck.com.br'
